### ISSUE TITLE
API Control

### ISSUE THREAD

**Issue by norton62** [pearlxcore/Huawei-Router-Tool#3]
This is amazing, wanted to thank you for creating this!

I have an issue when trying to change the 'iptype' in the API control. I only want it to use IPv4 but it is currently set to mode '2' which is IPv6.

When I post a change I get 'Error 125003 : ERROR_WRONG_SESSION_TOKEN'.

I saw that you can't make any changes until quarantine is over, but do you know how I can change this as there is no setting in the WebUI?

![image](https://user-images.githubusercontent.com/7104018/80161428-45400b80-85c8-11ea-8243-ffbe7b6635dd.png)

Any help would be great! - Using Huawei B525 Router

**Comment by pearlxcore** [comment]
Hi. The session error I already fixed but haven’t uploaded the latest binary. This error may appear on some model while trying to send POST request. I didn’t saw this error on E5577 but on B525 and B618 it appeared maybe because it using different method.

I once played with the api (api/dialup/profiles) while using E5577. Yes you can make changes to the request like adding new profile or even change profile setting. Im sure you can make changes for ip type too. 

At the moment Im not sure how you can change that value other than webui setting. Maybe you try curl command to send POST request to server.

**Comment by norton62** [comment]
Thanks for the reply!

I managed to change the setting by unhiding the setting in the HTML editor. I'm not sure why the developers hide these options.

**Comment by pearlxcore** [comment]
Awesome! . It will be nice if there is custom webui adding all the important setting.
